# Generated by Django 5.2.3 on 2025-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('tipo', models.CharField(choices=[('estoque', 'Estoque'), ('vendas', 'Vendas')], max_length=10)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DadosProcessados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=255)),
                ('venda_total', models.FloatField(default=0)),
                ('valor_total', models.FloatField(default=0)),
                ('media_mensal', models.FloatField(default=0)),
                ('estoque', models.FloatField(default=0)),
                ('pdv', models.FloatField(default=0)),
                ('cobertura', models.FloatField(default=0)),
                ('estoque_ideal', models.FloatField(default=0)),
                ('sugestao_abastecimento', models.FloatField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('prioridade', models.CharField(max_length=10)),
                ('data_processamento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dado Processado',
                'verbose_name_plural': 'Dados Processados',
                'ordering': ['-data_processamento', 'codigo'],
            },
        ),
    ]
