# Generated by Django 5.2.3 on 2025-06-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArquivoUpload',
        ),
        migrations.DeleteModel(
            name='DadosProcessados',
        ),
    ]
