# Generated by Django 5.2.3 on 2025-06-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtheusSB1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B1_FILIAL', models.CharField(max_length=2, verbose_name='Filial')),
                ('B1_COD', models.CharField(max_length=15, verbose_name='Código do Produto')),
                ('B1_DESC', models.CharField(max_length=100, verbose_name='Descrição do Produto')),
                ('B1_TIPO', models.CharField(max_length=2, verbose_name='Tipo do Produto')),
                ('B1_UM', models.CharField(max_length=2, verbose_name='Unidade de Medida')),
                ('B1_GRUPO', models.CharField(max_length=4, verbose_name='Grupo do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'SB1010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtheusSB2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B2_FILIAL', models.CharField(max_length=2, verbose_name='Filial')),
                ('B2_COD', models.CharField(max_length=15, verbose_name='Código do Produto')),
                ('B2_LOCAL', models.CharField(max_length=2, verbose_name='Local')),
                ('B2_QATU', models.FloatField(verbose_name='Quantidade Atual em Estoque')),
                ('B2_RESERVA', models.FloatField(verbose_name='Quantidade Reservada')),
                ('B2_QPEDVEN', models.FloatField(verbose_name='Quantidade em Pedido de Venda')),
            ],
            options={
                'verbose_name': 'Saldo em Estoque',
                'verbose_name_plural': 'Saldos em Estoque',
                'db_table': 'SB2010',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtheusSD3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D3_COD', models.CharField(max_length=15, verbose_name='Código do produto')),
                ('D3_TM', models.CharField(max_length=2, verbose_name='Tipo de movimento')),
                ('D3_EMISSAO', models.DateField(verbose_name='Data da movimentação')),
                ('D3_QUANT', models.FloatField(verbose_name='Quantidade movimentada')),
                ('D3_CF', models.CharField(max_length=10, verbose_name='Código fiscal')),
                ('D3_DOC', models.CharField(max_length=9, verbose_name='Documento')),
                ('D3_LOCAL', models.CharField(max_length=2, verbose_name='Local (depósito)')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'SD3010',
                'managed': False,
            },
        ),
    ]
