# Generated by Django 5.1.2 on 2025-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protheus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtheusSC9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C9_FILIAL', models.CharField(max_length=2, verbose_name='Filial')),
                ('C9_PEDIDO', models.CharField(max_length=6, verbose_name='Número do Pedido')),
                ('C9_ITEM', models.CharField(max_length=2, verbose_name='Item do Pedido')),
                ('C9_SEQUEN', models.CharField(max_length=3, verbose_name='Sequência')),
                ('C9_PRODUTO', models.CharField(max_length=15, verbose_name='Código do Produto')),
                ('C9_QTDLIB', models.FloatField(verbose_name='Quantidade Liberada')),
                ('C9_PRCVEN', models.FloatField(verbose_name='Preço de Venda')),
                ('C9_DATALIB', models.DateField(blank=True, null=True, verbose_name='Data de Liberação')),
                ('C9_LOCAL', models.CharField(max_length=2, verbose_name='Local/Armazém')),
                ('C9_LOTECTL', models.CharField(blank=True, max_length=10, null=True, verbose_name='Lote')),
                ('C9_NUMLOTE', models.CharField(blank=True, max_length=6, null=True, verbose_name='Sub-Lote')),
                ('C9_DTVALID', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('C9_POTENCI', models.FloatField(default=0, verbose_name='Potência')),
                ('C9_QTDLIB2', models.FloatField(default=0, verbose_name='Quantidade na 2ª UM')),
                ('C9_AGREG', models.CharField(blank=True, max_length=1, null=True, verbose_name='Agregado')),
                ('C9_SERVIC', models.CharField(blank=True, max_length=3, null=True, verbose_name='Código do Serviço')),
                ('C9_ORDSEP', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ordem de Separação')),
                ('C9_BLEST', models.CharField(blank=True, max_length=2, null=True, verbose_name='Bloqueio de Estoque')),
                ('C9_BLCRED', models.CharField(blank=True, max_length=2, null=True, verbose_name='Bloqueio de Crédito')),
                ('C9_OK', models.CharField(blank=True, max_length=2, null=True, verbose_name='Liberação OK')),
                ('C9_NFISCAL', models.CharField(blank=True, max_length=9, null=True, verbose_name='Nota Fiscal')),
                ('C9_SERIENF', models.CharField(blank=True, max_length=3, null=True, verbose_name='Série NF')),
                ('D_E_L_E_T', models.CharField(blank=True, db_column='D_E_L_E_T_', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Liberação/Entrega',
                'verbose_name_plural': 'Liberações/Entregas',
                'db_table': 'SC9010',
                'managed': False,
            },
        ),
    ]
